# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

variables:
  solution: '**/zimbelman-bryce-p1/StoreApp/*.sln'
  buildPlatform: 'Any CPU'
  buildConfigurtion: 'Release'

steps:
# Basic pipeline of restoring, building, and testing
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: $(solution)
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: $(solution)
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: '**/zimbelman-bryce-p1/StoreApp/StoreTests/*.csproj'